version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "CadisRaziel"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "CadisRaziel"
  - package-ecosystem: gradle
    directory: "/example/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "CadisRaziel"
  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "CadisRaziel"
